export const LAVOZIM_OPTIONS = [
  { label: "Boshqaruv Raisi", value: "rais" },
  { label: "Boshqaruv rais o'rinbosari", value: "rais_orinbosari" },
  { label: "Boshqarma boshlig'i", value: "boshqarma_boshi" },
  {
    label: "Boshqarma boshlig'i o'rinbosari",
    value: "boshqarma_boshligi_orinbosari",
  },
  { label: "Yetakchi muhandis", value: "yetakchi_muhandis" },
  { label: "Muhandis", value: "muhandis" },
  { label: "Uchastka Rahbari", value: "uchastka_rahbari" },
  { label: "PTO", value: "pto" },
  { label: "Buxgalter", value: "buxgalter" },
  { label: "Iqtisodchi", value: "iqtisod" },
  { label: "Kadrlar Xodimi", value: "kadr" },
  { label: "Muhandis", value: "xodim" },
];
export const UZBEKISTAN_LOCATIONS = {
  "Toshkent shahri": [
    "Yunusobod",
    "Chilonzor",
    "Mirzo Ulug'bek",
    "Shayxontohur",
    "Olmazor",
    "Bektemir",
    "Yakkasaroy",
    "Yashnobod",
    "Sergeli",
    "Uchtepa",
    "Hamza",
  ],
  "Toshkent viloyati": [
    "Angren",
    "Bekobod",
    "Bo'ka",
    "Bo'stonliq",
    "Chinoz",
    "Chirchiq",
    "Ohangaron",
    "Oqqo'rg'on",
    "Parkent",
    "Piskent",
    "Qibray",
    "Yangiyo'l",
    "Zangiota",
    "Zangota",
  ],
  Samarqand: [
    "Samarqand shahri",
    "Ishtixon",
    "Jomboy",
    "Kattaqo'rg'on",
    "Narpay",
    "Nurobod",
    "Oqdaryo",
    "Pastdarg'om",
    "Paxtachi",
    "Payariq",
    "Qo'shrabot",
    "Toyloq",
    "Urgut",
  ],
  Buxoro: [
    "Buxoro shahri",
    "G'ijduvon",
    "Jondor",
    "Kogon",
    "Olot",
    "Peshku",
    "Qorovulbozor",
    "Romitan",
    "Shofirkon",
    "Vobkent",
  ],
  "Farg'ona": [
    "Farg'ona shahri",
    "Beshariq",
    "Bog'dod",
    "Buvayda",
    "Dang'ara",
    "Furqat",
    "Hamza",
    "Marg'ilon",
    "O'zbekiston",
    "Oltiariq",
    "Qo'qon",
    "Quva",
    "Rishton",
    "So'x",
    "Toshloq",
    "Uchko'prik",
    "Yozyovon",
  ],
  Andijon: [
    "Andijon shahri",
    "Asaka",
    "Baliqchi",
    "Bo'z",
    "Buloqboshi",
    "Izboskan",
    "Jalaquduq",
    "Xo'jaobod",
    "Marhamat",
    "Oltinko'l",
    "Paxtaobod",
    "Qo'rg'ontepa",
    "Shahrixon",
    "Ulug'nor",
  ],
  Namangan: [
    "Namangan shahri",
    "Chortoq",
    "Chust",
    "Kosonsoy",
    "Mingbuloq",
    "Namangan tumani",
    "Norin",
    "Pop",
    "To'raqo'rg'on",
    "Uchqo'rg'on",
    "Yangiqo'rg'on",
  ],
  Xorazm: [
    "Urganch shahri",
    "Bog'ot",
    "Gurlan",
    "Hazorasp",
    "Xiva",
    "Xonqa",
    "Qo'shko'pir",
    "Shovot",
    "Urganch tumani",
    "Yang'iariq",
    "Yangibozor",
  ],
  Qashqadaryo: [
    "Qarshi shahri",
    "Chiroqchi",
    "Dehqonobod",
    "G'uzor",
    "Kasbi",
    "Kitob",
    "Koson",
    "Mirishkor",
    "Muborak",
    "Nishon",
    "Qamashi",
    "Shahrisabz",
    "Yakkabog'",
  ],
  Surxondaryo: [
    "Termiz shahri",
    "Angor",
    "Bandixon",
    "Boysun",
    "Denov",
    "Jarqo'rg'on",
    "Muzrabot",
    "Oltinsoy",
    "Qiziriq",
    "Qumqo'rg'on",
    "Sariosiyo",
    "Sherobod",
    "Sho'rchi",
    "Uzun",
  ],
  Jizzax: [
    "Jizzax shahri",
    "Arnasoy",
    "Baxmal",
    "Do'stlik",
    "Forish",
    "G'allaorol",
    "Mirzacho'l",
    "Paxtakor",
    "Sharof Rashidov",
    "Yangiobod",
    "Zafarobod",
    "Zarbdor",
    "Zomin",
  ],
  Sirdaryo: [
    "Guliston shahri",
    "Boyovut",
    "Gurushtepa",
    "Xovos",
    "Mirzaobod",
    "Oqoltin",
    "Sardoba",
    "Sayxunobod",
    "Shirin",
    "Yangiyer",
  ],
  Navoiy: [
    "Navoiy shahri",
    "Karmana",
    "Konimex",
    "Navbahor",
    "Nurota",
    "Qiziltepa",
    "Tomdi",
    "Uchquduq",
    "Xatirchi",
  ],
  "Qoraqalpog'iston": [
    "Nukus shahri",
    "Amudaryo",
    "Beruniy",
    "Chimboy",
    "Ellikkala",
    "Kegeyli",
    "Mo'ynoq",
    "Nukus tumani",
    "Qanliko'l",
    "Qo'ng'irot",
    "Qorao'zak",
    "Shumanay",
    "Taxtako'pir",
    "To'rtko'l",
    "Xo'jayli",
  ],
};
