// src/config/permissions.js

export const ROLES = {
  //   SUPERADMIN: "superadmin",
  MANAGER: "manager",
  BOSHQARMA: "boshqarma",
  VIEWER: "viewer",
  XODIM: "xodim",
  rais: "rais",
};

export const PERMISSIONS = {
  superadmin: {
    canCreate: true,
    canCreateTopshiriq: true,
    canCreateTalab: true,
    canAnswerTalab: true,
    canAnswerTopshiriq: true,
    canRead: true,
    canUpdate: true,
    canDelete: true,
    canManageUsers: true,
    canSeeUsers: true,
    canSeeTalablar: true,
  },
  rais: {
    canCreate: true,
    canCreateTopshiriq: true,
    canCreateTalab: true,
    canAnswerTalab: true,
    canAnswerTopshiriq: true,
    canRead: true,
    canUpdate: true,
    canDelete: true,
    canManageUsers: true,
    canSeeTalablar: true,
    rais: true,
  },
  rais_orinbosari: {
    canCreate: true,
    canCreateTopshiriq: true,
    canCreateBayonnoma: true,
    canCreateTalab: true,
    canAnswerTalab: true,
    canAnswerTopshiriq: true,
    canRead: true,
    canUpdate: true,
    canDelete: false,
    canManageUsers: true,
    canSeeUsers: true,
    canSeeTalablar: true,
  },
  boshqarma_boshi: {
    canCreate: true,
    canCreateTopshiriq: true,
    canCreateTalab: true,
    canAnswerTalab: true,
    canAnswerTopshiriq: true,
    canRead: true,
    canUpdate: true,
    canDelete: true,
    canManageUsers: true,
    canSeeTalablar: true,
  },
  boshqarma_boshligi_orinbosari: {
    canCreate: true,
    canCreateTopshiriq: true,
    canCreateTalab: true,
    canAnswerTalab: true,
    canAnswerTopshiriq: true,
    canRead: true,
    canUpdate: true,
    canDelete: false,
    canManageUsers: true,
    canSeeTalablar: true,
  },
  yetakchi_muhandis: {
    canCreate: false,
    canCreateTopshiriq: false,
    canCreateTalab: true,
    canAnswerTalab: true,
    canAnswerTopshiriq: true,
    canRead: true,
    canUpdate: false,
    canDelete: false,
    canManageUsers: false,
    canSeeTalablar: true,
  },
  muhandis: {
    canCreate: false,
    canCreateTopshiriq: false,
    canCreateTalab: false,
    canAnswerTalab: false,
    canAnswerTopshiriq: true,
    canRead: true,
    canUpdate: false,
    canDelete: false,
    canManageUsers: false,
    canSeeTalablar: true,
  },
  pto: {
    canCreate: false,
    canCreateTopshiriq: false,
    canAnswerTalab: true,
    canAnswerTopshiriq: true,
    canRead: true,
    canUpdate: false,
    canDelete: false,
    canManageUsers: false,
    canCreateTalab: true,
    canSeeTalablar: true,
  },
  boshqarma: {
    canCreate: true,
    canCreateTalab: true,
    canAnswerTalab: true,
    canAnswerTopshiriq: true,
    canRead: true,
    canUpdate: false,
    canDelete: false,
    canManageUsers: false,
    canSeeTalablar: true,
  },
  xodim: {
    canCreate: false,
    canCreateTopshiriq: false,
    canRead: true,
    canUpdate: false,
    canDelete: false,
    canManageUsers: false,
    canCreateTalab: false,
    canAnswerTalab: false,
    canAnswerTopshiriq: true,
    canSeeTalablar: true,
  },
  viewer: {
    canCreate: false,
    canCreateTopshiriq: false,
    canCreateTalab: false,
    canAnswerTalab: false,
    canAnswerTopshiriq: false,
    canRead: true,
    canUpdate: false,
    canDelete: false,
    canManageUsers: false,
    canSeeTalablar: false,
  },
};
